---
version: 1.2
workflows:
  - name: hBOTA
    subclass: WDL
    primaryDescriptorPath: /jwitch/hBOTA/hBOTA.wdl
  - name: NETMHC2_allele
    subclass: WDL
    primaryDescriptorPath: /jwitch/hBOTA/NETMHC2_allele.wdl
